### ISSUE TITLE
Using MOSEK in SOSTOOLS

### ISSUE THREAD

**Issue by Utkarsh-Detha** [sums-of-squares/tools#20]
The documents suggest that there is an interface between the MOSEK solver and SOSTOOLS. However, inspecting the source code for SOSTOOLS suggests that there is no support for MOSEK.

Can you throw some light on this matter? Did you mean that MOSEK's Optimization toolbox is an option for solving SOS problems in MATLAB, or did you mean that MOSEK is available as a solver within SOSTOOLS?

If indeed there is an interface, could you provide some instructions/examples on how to use it?

**Comment by yuanchenyang** [comment]
I think this is a mistake in the documentation, SOSTOOLS doesn't seem to support MOSEK as a backend solver. If you wish to use MOSEK, you might want to use [YALMIP](https://yalmip.github.io/tutorial/sumofsquaresprogramming/) or the Julia/Python interfaces.
